/**
 * @license
 * Copyright 2020 Carles Ferrando Garcia (ferrando_cariga@gva.es)
 * SPDX-License-Identifier: BSD-3-Clause
 */

var MSG = {
    title: "BDuino",
    appName: "BlocklyDuino",
    blocks: "Bloques",
    prog: "Programa",
    catLogic: "💡 Lógica",
    catLoops: "↻ Bucles",
    catMath: "+ Matemáticas",
    catText: "ℜ Texto",
    catLists: "☰ Listas",
    catColour: "🌈 Color",
    catVariables: "❓ Variables",
    catFunctions: "ƒ(x) Funciones",
    listVariable: "lista",
    textVariable: "texto",
    screenshot: "Descarga una captura de pantalla",
    xmlError: "No se puede descargar vuestro fichero guardado. Quizás se ha creado con un versión diferente de BlocklyDuino?",
    badXml: "Error de análisis XML:\n%1\n\nSelecciona 'De acuerdo' para abandonar los cambios o 'Cancela' para continuar editando el fichero.",
    languageSpan: "escoge idioma",
    interfaceColorSpan: "tema de interface",
    codeEditorColorSpan: "tema del editor codigo",
    themeSpan: "escoge tema",
    renderSpan: "escoge renderizador",
    fullScreenButton_span: "pantalla completa",
    undoButton_span: "Deshacer",
    redoButton_span: "Rehacer",
    boardSpan: "escoge tu placa Arduino",
    boardButtonSpan: "lista de placas",
    verifyButton_span: "Verificar el código",
    serialSpan: "escoge puerto COM",
    serialButtonSpan: "lista puerto COM",
    uploadButton_span: "Cargar",
    serialConnectButton_span: "Monitor serie",
    saveCodeButton_span: "Exportar código Arduino",
    newButton_span: "Proyecto nuevo",
    save_span: "Guardar nombre de archivo?",
    saveXMLButton_span: "Guardar fichero BlocklyDuino",
    loadXMLfakeButton_span: "Cargar fichero BlocklyDuino",
    loadXML_span: "Remplazar bloques existentes?\n'Cancelar' Mezclar.",
    loadXML_error_span: "Error análisis XML:\n",
    resetButton_span: "Restablece BlocklyDuino",
    resetQuestion_span: "Resetear BlocklyDuino y",
    helpButton_span: "ayuda",
    helpModalSpan_title: "Ayuda - Acerca",
    helpModalSpan_text:
        '<table>' +
        '<tbody>' +
        '<tr>' +
        '<td style="width: 142px;"><img src="./blocklyduino/media/logo_only.png" alt="" width="129" height="144" /></td>' +
        '<td>' +
        '<p style="text-align: left;"><strong>BlocklyDuino</strong></p>' +
        '<p style="text-align: left;">BlocklyDuino is a <strong>web program for editing and visual block programming for <a href="https://www.arduino.cc/">Arduino</a> boards</strong>. It is based on <a href="https://developers.google.com/blockly/">Blockly</a>, the graphical online programming editor and on the work done on <a href="https://github.com/A-S-T-U-C-E/STudio4Education">STudio4Education</a>, a similar project for <a href="https://www.st.com/">STmicroelectronics</a> boards.</p>' +
        '<p style="text-align: left;">BlocklyDuino provides a block programming environment and their translation into \'Arduino\' C code.</p>' +
        '</td>' +
        '</tr>' +
        '</tbody>' +
        '</table>' +
        '<p style="text-align: left;">Accessibility: <a href="https://github.com/BlocklyDuino/BlocklyDuino-v2#accessibility">online documentation</a>.</p>' +
        '<p style="text-align: left;">Official documentation: <a href="https://developers.google.com/blockly/guides/configure/web/keyboard-nav" rel="nofollow">Blockly developers</a>.</p>' +
        '<p style="text-align: left;">Wiki: <a href="http://www.libreduc.cc/wiki">on LibrEduc</a>.</p>' +
        '<p style="text-align: left;">A bug? Post it here: <a href="https://github.com/BlocklyDuino/BlocklyDuino-v2/issues">on Github</a>.</p>' +
        '<p style="text-align: center;">v0.7.3 - license GNU GPL version 3',
    editorReadOnlyToggle_span: "codigo editor editable o solo de lectura",
    copyCodeButton_span: "Copiar código a  portapapeles",
    accessibilitySpan: "habilitar modo accesibilidad",
    defaultCursorSpan: "Cursor por defecto",
    basicCursorSpan: "Cursor básico",
    lineCursorSpan: "Cursor linea",
    keyMappingSpan: "abrir asignaciones de teclado",
    themeClassicSpan: "Clásico",
    themeModernSpan: "Moderno",
    themeDeuteranopiaSpan: "Deuteranopia/Protanopia",
    themeTritanopiaSpan: "Tritanopia",
    themeZelosSpan: "Zelos",
    themeHighContrastSpan: "Alto contraste",
    themeDarkSpan: "Oscuro",
    themeBwSpan: "Negro & Blanco",
    compilationInProgress: "Placa",
    keyMappingModalSpan: "Establece asignaciones de teclado",
    detailedCompilation_span: "Compilación detallada con mensajes",
    CLI_title_span: "Configura Arduino CLI",
    installBoard_title_span: "instalar placa al CLI",
    searchlLib_title_span: "buscar una biblioteca",
    installLib_title_span: "instalar biblioteca al CLI",
    actionName0: "previo",
    actionName1: "siguiente",
    actionName2: "entra al bloque",
    actionName3: "sal del bloque",
    actionName4: "inserte",
    actionName5: "marca",
    actionName6: "desconectar",
    actionName7: "Caja de herramientas",
    actionName8: "salida",
    actionName9: "mueve el espacio de trabajo arriba",
    actionName10: "mueve el espacio de trabajo abajo",
    actionName11: "mueve el espacio de trabajo a izquierda",
    actionName12: "mueve el espacio de trabajo a derecha",
    actionName13: "conmuta el teclado de navegación",
    setup_sideButton_span: "configura",
    fontSizeSpan: "renderización",
    optionFontSizeBlocks: "Tamaño del tipo de letra bloques",
    optionFontSizePage: "Tamaño del tipo de letra página",
    optionFontSpacingPage: "Espaciado de letra página",
    //CLI_functions.js
    config_sideButton_span: "Control del compilador Arduino CLI",
    CLI_githubLinkButton_span: "documentación",
    coreUpdateButton_msg: "Se está actualizando...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    cleanCLIcacheButton_msg: "Se está limpiando...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    cleanCLIcacheButton_error_msg: "Error suprimiendo la carpeta .\\tmp",
    cleanCLIcacheButton_success_msg: "Limpiado!",
    listBoardsButton_msg: "Se está buscando la placa...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    installBoardsButton_msg: "Se está instalando el soporte de la placa, espera...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    searchlLibButton_msg: "Se está buscando la biblioteca...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    installLibButton_msg: "Se está instalando la biblioteca...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    coreUpdateButton_span: "actualizar núcleo y bibliotecas",
    cleanCLIcacheButton_span: "Se está limpiando caché",
    listBoardsButton_span: "detección y listado de placas",
    installBoardsInput_span: "nombre de la placa a soportar",
    installBoardsButton_span: "instalar este tipo de placa",
    searchlLibInput_span: "nombre de la biblioteca a buscar",
    searchlLibButton_span: "buscar esta biblioteca",
    installLibInput_span: "nombre de la biblioteca a instalar",
    installLibButton_span: "instalar esta biblioteca",
    //IDE_functions.js
    IDE_connect: 'Conectar a placa ',
    IDE_select_port: 'Seleccionar el puerto !',
    IDE_select_board: 'Seleccionar la placa  !',
    IDE_verif_progress: '\nVerificación: in progress...\n<i class="fa fa-spinner fa-pulse fa-1_5x fa-fw"></i>',
    IDE_verif_ok: '\nVerificación: OK',
    IDE_upload1: 'Placa ',
    IDE_upload2: ' en puerto ',
    IDE_upload3: '\nUpload: in progress...\n<i class="fa fa-spinner fa-pulse fa-1_5x fa-fw"></i>',
    IDE_upload_ok: '\nUpload: OK',
    serial_btn_start: "<span class='fa fa-play'></span> Empezar",
    serial_info_stop: 'stop<br>',
    serial_btn_stop: "<span class='fa fa-pause'></span> Detener",
    serial_info_start: 'inicio de comunicación<br>',
    serial_CSV: 'Export data to CSV',
    inputTextSerial: 'Texto',
    btn_serialSend_span: 'Enviar',
    btn_serialConnect_span: 'Empezar',
    btn_serialPeekClear_span: 'Limpiar',
    btn_serialPeekCSV_span: 'Exportar',
    btn_serialChart_span: 'Graficar',
    btn_serialChartPause_span: 'Empezar'
};
