var MSG = {
    blocks: "Blocks",
    catLogic: "Logic",
    catLoops: "Loops",
    catMath: "Math",
    catText: "Text",
    catLists: "Lists",
    catColour: "Colour",
    catVariables: "Variables",
    catFunctions: "Functions",
    listVariable: "list",
    textVariable: "text",
    xmlError: "Could not load your saved file. Perhaps it was created with a different version of S4E?",
    badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the file.",
    languageSpan: "choose language",
    themeSpan: "choose  theme",
    renderSpan: "choose renderer",
    boardSpan: "choose board",
    serialSpan: "choose COM port",
    undoButton_span: "Undo",
    redoButton_span: "Redo",
    verifyButton_span: "Verify code",
    uploadButton_span: "Upload",
	serialConnectButton_span: "Serial monitor",
    saveCodeButton_span: "Export Arduino Code",
    newButton_span: "New project",
    saveXMLButton_span: "Save to BlocklyDuino file",
    loadXMLfakeButton_span: "Load BlocklyDuino file",
    resetButton_span: "Reset BlocklyDuino",
    helpButton_span: "About",
    accessibilitySpan: "Enable Accessibility Mode:",
    defaultCursorSpan: "Default Cursor",
    basicCursorSpan: "Basic Cursor",
    lineCursorSpan: "Line Cursor",
    keyMappingSpan: "Open Key Mappings",
    themeClassicSpan: "Classic",
    themeModernSpan: "Modern",
    themeDeuteranopiaSpan: "Deuteranopia/Protanopia",
    themeTritanopiaSpan: "Tritanopia",
    themeZelosSpan: "Zelos",
    themeHighContrastSpan: "High Contrast",
    themeDarkSpan: "Dark",
    themeBwSpan: "Black & White",
    keyMappingModalSpan: "Set key mappings",
    accessibilityExplanationSpan: "You can enter accessibility mode by <b>shift clicking anywhere on the workspace or on a block</b>. <br /><br /><b>Workspace Navigation</b><br />W: Previous block/field/input at the same level<br />A: Up one level (Field (or input) -&gt; Block -&gt; Input (or field) -&gt; Block -&gt; Stack -&gt; Workspace)<br />S: Next block/field/input at the same level<br />D: Down one level (Workspace -&gt; Stack -&gt; Block -&gt; Input (or field) -&gt; Block -&gt; Field (or input))<br />T: Will open the toolbox. Once in there you can moving around using the WASD keys. And insert a block by hitting Enter<br />X: While on a connection hit X to disconnect the block after the cursor<br /><br /><b>Cursor</b><br /><b>Default Cursor:</b> Allow the user to go to the previous, next, in or out location.<br /><b>Basic Cursor:</b> Using the pre order traversal allows the user to go to the next and previous location.</td>",
    actionName0: "previous",
    actionName1: "next",
    actionName2: "in",
    actionName3: "out",
    actionName4: "insert",
    actionName5: "mark",
    actionName6: "disconnect",
    actionName7: "toolbox",
    actionName8: "exit",
    actionName9: "move workspace cursor up",
    actionName10: "move workspace cursor down",
    actionName11: "move workspace cursor left",
    actionName12: "move workspace cursor right",
    actionName13: "toggle keyboard navigation",
    aboutHelpModalSpan: "about BlocklyDuino project",
    aboutHelpModalContentSpan: "<p style='text-align: center;'><em>Help : <a href='https://github.com/BlocklyDuino/BlocklyDuinoReboot'>https://github.com/BlocklyDuino/BlocklyDuinoReboot</a></em></p><p>BlocklyDuino is a <strong>web-based visual programming editor for <a href='http://www.arduino.cc/' rel='nofollow'>Arduino</a></strong>.</p><p>BlocklyDuino is based on <a href='https://developers.google.com/blockly/' rel='nofollow'>Blockly</a>, the web-based, graphical programming editor. Provide static type language blocks and code generators for Arduino programming.</p><p><a href='https://raw.githubusercontent.com/BlocklyDuino/BlocklyDuinoReboot/master/blockly_logos/logo_built_on.png' target='_blank' rel='noopener noreferrer'><img style='max-width: 100%; display: block; margin-left: auto; margin-right: auto;' src='https://raw.githubusercontent.com/BlocklyDuino/BlocklyDuinoReboot/master/blockly_logos/logo_built_on.png' alt='' width='305' height='110' /></a>BlocklyDuino also support <a href='http://www.seeedstudio.com/wiki/GROVE_System' rel='nofollow'>Grove</a> blocks to easily get started with microcontroller-based experimentation and learning.</p><h3>Authors and Contributors</h3><p>S&eacute;bastien Canet (<a href='mailto:scanet@libreduc.cc'>scanet@libreduc.cc</a>) for this reboot and Electron version.</p><p>Fred Lin (@gasolin) for original BlocklyDuino.</p><p>Thanks Neil Fraser, Q.Neutron from Blockly <a href='https://developers.google.com/blockly/' rel='nofollow'>https://developers.google.com/blockly/</a></p><p>Thanks Arduino and Seeeduino guys for Arduino and Grove blocks.</p><p>The project is also inspired by <a href='https://github.com/taweili/ardublock'>ardublock</a> and <a href='http://www.modk.it/' rel='nofollow'>modkit</a></p>"
};
