var MSG = {
    blocks: "Blocks",
    catLogic: "Logic",
    catLoops: "Loops",
    catMath: "Math",
    catText: "Text",
    catLists: "Lists",
    catColour: "Colour",
    catVariables: "Variables",
    catFunctions: "Functions",
    listVariable: "list",
    textVariable: "text",
    xmlError: "Could not load your saved file. Perhaps it was created with a different version of S4E?",
    badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the file.",
    languageSpan: "choose language",
    themeSpan: "choose  theme",
    renderSpan: "choose renderer",
    undoButton_span: "Undo",
    redoButton_span: "Redo",
    boardSpan: "choose Arduino board",
    verifyButton_span: "Verify code",
    serialSpan: "choose COM port",
    uploadButton_span: "Upload",
	viewCodeButton_span: "Code peek",
	serialConnectButton_span: "Serial monitor",
    saveCodeButton_span: "Export Arduino Code",
    newButton_span: "New project",
    saveXMLButton_span: "Save to BlocklyDuino file",
    loadXMLfakeButton_span: "Load BlocklyDuino file",
    resetButton_span: "Reset BlocklyDuino",
    helpButton_span: "help",
    accessibilitySpan: "enable Accessibility Mode:",
    defaultCursorSpan: "Default Cursor",
    basicCursorSpan: "Basic Cursor",
    lineCursorSpan: "Line Cursor",
    keyMappingSpan: "open key mappings",
    themeClassicSpan: "Classic",
    themeModernSpan: "Modern",
    themeDeuteranopiaSpan: "Deuteranopia/Protanopia",
    themeTritanopiaSpan: "Tritanopia",
    themeZelosSpan: "Zelos",
    themeHighContrastSpan: "High Contrast",
    themeDarkSpan: "Dark",
    themeBwSpan: "Black & White",
    keyMappingModalSpan: "Set key mappings",
    detailedCompilation_span: "Detailed compilation verbose",
    accessibilityExplanationSpan: "You can enter accessibility mode by <b>shift clicking anywhere on the workspace or on a block</b>. <br /><br /><b>Workspace Navigation</b><br />W: Previous block/field/input at the same level<br />A: Up one level (Field (or input) -&gt; Block -&gt; Input (or field) -&gt; Block -&gt; Stack -&gt; Workspace)<br />S: Next block/field/input at the same level<br />D: Down one level (Workspace -&gt; Stack -&gt; Block -&gt; Input (or field) -&gt; Block -&gt; Field (or input))<br />T: Will open the toolbox. Once in there you can moving around using the WASD keys. And insert a block by hitting Enter<br />X: While on a connection hit X to disconnect the block after the cursor<br /><br /><b>Cursor</b><br /><b>Default Cursor:</b> Allow the user to go to the previous, next, in or out location.<br /><b>Basic Cursor:</b> Using the pre order traversal allows the user to go to the next and previous location.</td>",
    actionName0: "previous",
    actionName1: "next",
    actionName2: "in",
    actionName3: "out",
    actionName4: "insert",
    actionName5: "mark",
    actionName6: "disconnect",
    actionName7: "toolbox",
    actionName8: "exit",
    actionName9: "move workspace cursor up",
    actionName10: "move workspace cursor down",
    actionName11: "move workspace cursor left",
    actionName12: "move workspace cursor right",
    actionName13: "toggle keyboard navigation",
    setup_sideButton_span: "setup",
    fontSizeSpan: "rendering",
    optionFontSize: "Font Size",
    keyMappingExplanationSpan: "<p>You can enter <em>accessibility </em>mode by <strong>shift clicking anywhere on the workspace</strong> or on a block.</p><p>Key mapping is customizable by activating it.</p><p>You can acces more complete <strong>documentation </strong>by <strong><a href='https://github.com/BlocklyDuino/BlocklyDuino-v2' target='_blank'>clicking on '?'</a></strong>.</span></p>"
};
