var MSG = {
    title: "BlocklyDuino",
    appName: "BlocklyDuino",
    blocks: "Blocs",
    prog: "Programme",
    catLogic: "💡 Logique",
    catLoops: "↻ Boucles",
    catMath: "+ Math",
    catText: "ℜ Texte",
    catLists: "☰ Listes",
    catColour: "🌈 Couleurs",
    catVariables: "❓ Variables",
    catFunctions: "ƒ(x) Fonctions",
    // listVariable: "liste",
    // textVariable: "texte",
    screenshot: "Télécharger une capture d'écran",
    xmlError: "Impossible de charger le fichier de sauvegarde.  Peut être a t-il été créé avec une autre version de Blockly ?",
    badXml: "Erreur d’analyse du fichier :\n%1\n\nSélectionner 'OK' pour abandonner vos modifications ou 'Annuler' pour continuer à modifier le fichier.",
    languageSpan: "choix de la langue",
    themeSpan: "choix du thème",
    renderSpan: "choix de la forme",
    fullScreenButton_span: "plein écran",
    undoButton_span: "annuler",
    redoButton_span: "refaire",
    boardSpan: "choix de la carte",
    verifyButton_span: "compiler le code",
    serialSpan: "choix du port COM",
    uploadButton_span: "téléverser",
    serialConnectButton_span: "moniteur série",
    saveCodeButton_span: "exporte le code",
    newButton_span: "nouveau projet",
    saveXMLButton_span: "enregistrer le fichier Blockly",
    loadXMLfakeButton_span: "ouvrir un fichier Blockly",
    loadXML_span: "Remplacer les blocs déjà présents ?\n'Annuler' les rajoutera.",
    loadXML_error_span: "Erreur dans le fichier Blockly :\n",
    resetButton_span: "réinitialiser BlocklyDuino",
    helpButton_span: "aide",
    copyCodeButton_span: "copier le code dans le presse papiers",
    accessibilitySpan: "activer le contrôle clavier :",
    defaultCursorSpan: "curseur par défaut",
    basicCursorSpan: "curseur classique",
    lineCursorSpan: "curseur ligne",
    keyMappingSpan: "attribution des touches",
    themeClassicSpan: "classique",
    themeModernSpan: "moderne",
    themeDeuteranopiaSpan: "Deuteranopia/Protanopia",
    themeTritanopiaSpan: "Tritanopia",
    themeZelosSpan: "Zelos",
    themeHighContrastSpan: "Contraste élevé",
    themeDarkSpan: "Sombre",
    themeBwSpan: "Noir & Blanc",
    compilationInProgress: "Carte",
    keyMappingModalSpan: "Attrbution des touches",
    detailedCompilation_span: "Résultats détaillés",
    CLI_title_span: "compilateur - gestion",
    installBoard_title_span: "cartes à rajouter",
    searchlLib_title_span: "recherche de bibliothèque",
    installLib_title_span: "installation de biblitohèque",
    actionName0: "précédent",
    actionName1: "suivant",
    actionName2: "rentrer dans le bloc",
    actionName3: "sortir du bloc",
    actionName4: "insérer",
    actionName5: "marquer",
    actionName6: "détacher le bloc",
    actionName7: "menu",
    actionName8: "sortie",
    actionName9: "espace de travail vers le haut",
    actionName10: "espace de travail vers le bas",
    actionName11: "espace de travail vers la gauche",
    actionName12: "espace de travail vers la droite",
    actionName13: "basculer la navigation clavier",
    setup_sideButton_span: "configuration",
    fontSizeSpan: "rendu",
    optionFontSizeBlocks: "police das blocs",
    optionFontSizePage: "taille des écritures",
    optionFontSpacingPage: "espacement entre les lettres",
    keyMappingExplanationSpan: "<p>Vous pouvez activer le mode <em>accessibilité </em>en appuyant sur les touches <strong>Shift + Ctrl + k</strong>.</p><p>L'attribution des touches est paramétrable en activant son panneau.</p><p>Une <strong>documentation </strong> plus complète est consultable en <strong><a href='https://github.com/BlocklyDuino/BlocklyDuino-v2' target='_blank'>cliquant sur le '?'</a></strong>.</span></p>",
    //CLI_functions.js
    config_sideButton_span: "gestion du compilateur",
    CLI_githubLinkButton_span: "documentation",
    coreUpdateButton_msg: "Mise à jour en cours...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    cleanCLIcacheButton_msg: "Nettoyage en cours...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    cleanCLIcacheButton_error_msg: "Erreur de suppression du dossier .\\tmp",
    cleanCLIcacheButton_success_msg: "Nettoyage effectué",
    listBoardsButton_msg: "Recherche de cartes en cours...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    installBoardsButton_msg: "Installation en cours, patience...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    searchlLibButton_msg: "Recherche de bibliothèque en cours...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    installLibButton_msg: "Installation de la bibliothèque en cours...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    coreUpdateButton_span: "mise à jour des définitions et des bibliothèques",
    cleanCLIcacheButton_span: "nettoyage du cache",
    listBoardsButton_span: "détection et liste des cartes connectées",
    installBoardsInput_span: "taper le nom exact du type de carte à prendre à charge",
    installBoardsButton_span: "installer ce type de cartes",
    searchlLibInput_span: "taper le nom exact de la bibliothèque à chercher",
    searchlLibButton_span: "chercher cette bibliothèque",
    installLibInput_span: "taper le nom exact de la bibliothèque à installer",
    installLibButton_span: "installer cette bibliothèque",
    //IDE_functions.js
    IDE_connect: 'Connexion au port ',
    IDE_select_port: 'Sélectionner un port COM !!!',
    IDE_select_board: 'Sélectionner une carte !',
    IDE_verif_progress: '\nVérification : en cours...\n<i class="fa fa-spinner fa-pulse fa-1_5x fa-fw"></i>',
    IDE_verif_ok: '\nVérification : OK',
    IDE_upload1: 'Carte ',
    IDE_upload2: ' sur port ',
    IDE_upload3: '\nTéléversement : en cours...\n<i class="fa fa-spinner fa-pulse fa-1_5x fa-fw"></i>',
    IDE_upload_ok: '\nTéléversement : OK',
    serial_btn_start: "<span class='fa fa-play'></span> Démarrer",
    serial_info_stop: 'arrêt<br>',
    serial_btn_stop: "<span class='fa fa-pause'></span> Arrêter",
    serial_info_start: 'démarrage de la communication<br>',
    serial_CSV: 'Exporter les données au format CSV',
    btn_serialSend_span: 'Envoyer',
    btn_serialConnect_span: 'Démarrer',
    btn_serialPeekClear_span: 'Effacer',
    btn_serialPeekCSV_span: 'Exporter',
    btn_serialChart_span: 'Graphique',
    btn_serialChartPause_span: 'Démarrer'
};